#
# Copyright 2017-2018 Amazon.com, Inc. or its affiliates. All Rights Reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License").
# You may not use this file except in compliance with the License.
# A copy of the License is located at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# or in the "license" file accompanying this file. This file is distributed
# on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either
# express or implied. See the License for the specific language governing
# permissions and limitations under the License.
#

AWSTemplateFormatVersion: 2010-09-09
Description: Sets up the RuleSet
Parameters:
  SourceLambdaBucket:
    Type: String
    Description: Bucket name where lambda code zips are placed
    MaxLength: 63
    MinLength: 3
    ConstraintDescription: Enter the name not the ARN, must be in the same region than the stack
  LambdaRuleIAMRoleARN:
    Type: String
    Description: IAM Role used by Lambda
  EmailAddressForComplianceNotifications:
    ConstraintDescription: Enter email address to which notifications will be sent
    Description: Email address to which notifications will be sent.
    Type: String
    Default: ''

Resources:

#
# BEGINNING OF THE RESOURCES SECTION TO BE ADAPTED TO YOUR NEEDS
# Modify your rule set here (sample below). Each new Custom Config rule of the ruleSet needs 1) Lambda Function and 2) Lambda Permission
# For managed rules, the configuration is to be done in application-account-setup.yaml
#

  CreateIAMRuleStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Join ['/', ['https://s3.amazonaws.com', !Ref SourceLambdaBucket, 'compliance-account-rule-lambda-setup.yaml']]
      Parameters:
        RuleSetName: SecurityEpic1-Identity_and_Access_Management
        SourceLambdaBucket: !Ref SourceLambdaBucket
        LambdaRuleRoleARN: !Ref LambdaRuleIAMRoleARN

  CreateLMRuleStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Join ['/', ['https://s3.amazonaws.com', !Ref SourceLambdaBucket, 'compliance-account-rule-lambda-setup.yaml']]
      Parameters:
        RuleSetName: SecurityEpic2-Logging_and_Monitoring
        SourceLambdaBucket: !Ref SourceLambdaBucket
        LambdaRuleRoleARN: !Ref LambdaRuleIAMRoleARN

  CreateISRuleStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Join ['/', ['https://s3.amazonaws.com', !Ref SourceLambdaBucket, 'compliance-account-rule-lambda-setup.yaml']]
      Parameters:
        RuleSetName: SecurityEpic3-Infrastructure_Security
        SourceLambdaBucket: !Ref SourceLambdaBucket
        LambdaRuleRoleARN: !Ref LambdaRuleIAMRoleARN

  CreateDPRuleStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Join ['/', ['https://s3.amazonaws.com', !Ref SourceLambdaBucket, 'compliance-account-rule-lambda-setup.yaml']]
      Parameters:
        RuleSetName: SecurityEpic4-Data_Protection
        SourceLambdaBucket: !Ref SourceLambdaBucket
        LambdaRuleRoleARN: !Ref LambdaRuleIAMRoleARN

  # CreateRRuleStack:
    # Type: AWS::CloudFormation::Stack
    # Properties:
      # TemplateURL: !Join ['/', ['https://s3.amazonaws.com', !Ref SourceLambdaBucket, 'compliance-account-rule-lambda-setup.yaml']]
      # Parameters:
        # RuleSetName: SecurityEpic6-Resilience
        # SourceLambdaBucket: !Ref SourceLambdaBucket
        # LambdaRuleRoleARN: !Ref LambdaRuleIAMRoleARN

#
# END OF THE RESOURCES SECTION TO BE ADAPTED
#

  CreateRuleSetReporterStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Join ["/", ["https://s3.amazonaws.com", !Ref SourceLambdaBucket, "compliance-account-rule-lambda-setup.yaml"]]
      Parameters:
        RuleSetName: SecurityEpic7-Compliance_Validation
        SourceLambdaBucket: !Ref SourceLambdaBucket
        LambdaRuleRoleARN: !Ref LambdaRuleIAMRoleARN
        CreateSnsTopicForComplianceNotifications: "Yes"
        EmailAddressForComplianceNotifications: !Ref EmailAddressForComplianceNotifications